<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Truncate the permissions table to remove existing records
        DB::table('permissions')->truncate();

        $permissions = [
            ['title' => 'show_status', 'display_title' => 'View Status', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_status', 'display_title' => 'Add Status', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_status', 'display_title' => 'Edit Status', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_status', 'display_title' => 'Delete Status', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_city', 'display_title' => 'View City', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_city', 'display_title' => 'Add City', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_city', 'display_title' => 'Edit City', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_city', 'display_title' => 'Delete City', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_client', 'display_title' => 'View Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_client', 'display_title' => 'Add Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_client', 'display_title' => 'Edit Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_client', 'display_title' => 'Delete Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_balances', 'display_title' => 'View Balances', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balances', 'display_title' => 'Add Balances', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balances', 'display_title' => 'Edit Balances', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balances', 'display_title' => 'Delete Balances', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_delegate', 'display_title' => 'View Delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_delegate', 'display_title' => 'Add Delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_delegate', 'display_title' => 'Edit Delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_delegate', 'display_title' => 'Delete Delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'distribution_order', 'display_title' => 'distribution Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_order', 'display_title' => 'Delete Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_requestJoin', 'display_title' => 'View Request Join', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_requestJoin', 'display_title' => 'Delete Request Join', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_follow', 'display_title' => 'View Follow', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_adminSetting', 'display_title' => 'Edit Admin Setting', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_role', 'display_title' => 'View Role', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_role', 'display_title' => 'Add Role', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_role', 'display_title' => 'Edit Role', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_role', 'display_title' => 'Delete Role', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_user', 'display_title' => 'View User', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_user', 'display_title' => 'Add User', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_user', 'display_title' => 'Edit User', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_user', 'display_title' => 'Delete User', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_slider', 'display_title' => 'View Slider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_slider', 'display_title' => 'Add Slider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_slider', 'display_title' => 'Edit Slider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_slider', 'display_title' => 'Delete Slider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_page', 'display_title' => 'View Page', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_page', 'display_title' => 'Add Page', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_page', 'display_title' => 'Edit Page', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_page', 'display_title' => 'Delete Page', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_post', 'display_title' => 'View Post', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_post', 'display_title' => 'Add Post', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_post', 'display_title' => 'Edit Post', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_post', 'display_title' => 'Delete Post', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_category', 'display_title' => 'View Category', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_category', 'display_title' => 'Add Category', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_category', 'display_title' => 'Edit Category', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_category', 'display_title' => 'Delete Category', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_service', 'display_title' => 'View Service', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_service', 'display_title' => 'Add Service', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_service', 'display_title' => 'Edit Service', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_service', 'display_title' => 'Delete Service', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_whatWeDo', 'display_title' => 'View What We Do', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_whatWeDo', 'display_title' => 'Add What We Do', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_whatWeDo', 'display_title' => 'Edit What We Do', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_whatWeDo', 'display_title' => 'Delete What We Do', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_branch', 'display_title' => 'View Branch', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_branch', 'display_title' => 'Add Branch', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_branch', 'display_title' => 'Edit Branch', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_branch', 'display_title' => 'Delete Branch', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_contactUs', 'display_title' => 'View Contact Us', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_contactUs', 'display_title' => 'Delete Contact Us', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_websiteSetting', 'display_title' => 'Edit Website Setting', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_rate', 'display_title' => 'View rate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_rate', 'display_title' => 'Add rate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_rate', 'display_title' => 'Edit rate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_rate', 'display_title' => 'Delete rate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_neighborhood', 'display_title' => 'show_neighborhood', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_neighborhood', 'display_title' => 'add_neighborhood', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_neighborhood', 'display_title' => 'edit_neighborhood', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_neighborhood', 'display_title' => 'delete_neighborhood', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_resturant', 'display_title' => 'show_resturant', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_resturant', 'display_title' => 'add_resturant', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_resturant', 'display_title' => 'edit_resturant', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_resturant', 'display_title' => 'delete_resturant', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_delegate_res', 'display_title' => 'show_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_delegate_res', 'display_title' => 'add_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_delegate_res', 'display_title' => 'edit_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_delegate_res', 'display_title' => 'delete_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_invoice', 'display_title' => 'show_invoice', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_invoice', 'display_title' => 'add_invoice', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_invoice', 'display_title' => 'edit_invoice', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_invoice', 'display_title' => 'delete_invoice', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_order_res', 'display_title' => 'show_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_order_res', 'display_title' => 'add_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_order_res', 'display_title' => 'edit_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_order_res', 'display_title' => 'delete_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_balance_res', 'display_title' => 'show_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balance_res', 'display_title' => 'add_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balance_res', 'display_title' => 'edit_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balance_res', 'display_title' => 'delete_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_balance_delegate', 'display_title' => 'show_balance_delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balance_delegate', 'display_title' => 'add_balance_delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balance_delegate', 'display_title' => 'edit_balance_delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balance_delegate', 'display_title' => 'delete_balance_delegate', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_balance_delegate_res', 'display_title' => 'show_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balance_delegate_res', 'display_title' => 'add_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balance_delegate_res', 'display_title' => 'edit_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balance_delegate_res', 'display_title' => 'delete_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_dailyReport', 'display_title' => 'show_dailyReport', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_dailyReport', 'display_title' => 'add_dailyReport', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_dailyReport', 'display_title' => 'edit_dailyReport', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_dailyReport', 'display_title' => 'delete_dailyReport', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_supervisor', 'display_title' => 'show supervisor', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_supervisor', 'display_title' => 'add supervisor', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_supervisor', 'display_title' => 'edit_supervisor', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_supervisor', 'display_title' => 'delete_supervisor', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_service_provider', 'display_title' => 'show_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_service_provider', 'display_title' => 'add service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_service_provider', 'display_title' => 'edit_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_service_provider', 'display_title' => 'delete_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_partner', 'display_title' => 'show_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_partner', 'display_title' => 'add_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_partner', 'display_title' => 'edit_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_partner', 'display_title' => 'delete_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_warehouse_branches', 'display_title' => 'show_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_warehouse_branches', 'display_title' => 'add_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_warehouse_branches', 'display_title' => 'edit_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_warehouse_branches', 'display_title' => 'delete_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_goods', 'display_title' => 'show_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_goods', 'display_title' => 'add_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_goods', 'display_title' => 'edit_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_goods', 'display_title' => 'delete_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_sizes', 'display_title' => 'show_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_sizes', 'display_title' => 'add_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_sizes', 'display_title' => 'edit_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_sizes', 'display_title' => 'delete_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'QR_print', 'display_title' => 'show_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_offers', 'show_offers' => 'show_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_offers', 'add_offers' => 'add_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_offers', 'edit_offers' => 'edit_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_offers', 'delete_offers' => 'delete_partner', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_pickup_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_pickup_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_pickup_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_pickup_order', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_return_order', 'display_title' => 'show_return_order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_return_order', 'display_title' => 'add_return_order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_return_order', 'display_title' => 'edit_return_order ', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_return_order', 'display_title' => 'delete_return_order ', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_return_order_res', 'display_title' => 'show_return_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_return_order_res', 'display_title' => 'add_return_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_return_order_res', 'display_title' => 'edit_return_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_return_order_res', 'display_title' => 'delete_return_order_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_client_warehouse', 'display_title' => 'View Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_client_warehouse', 'display_title' => 'Add Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_client_warehouse', 'display_title' => 'Edit Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_client_warehouse', 'display_title' => 'Delete Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_api_client', 'display_title' => 'View Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_api_client', 'display_title' => 'Add Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_api_client', 'display_title' => 'Delete Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'change_status', 'display_title' => 'change_status', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'assign_service_provider', 'display_title' => 'assign_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_history_order', 'display_title' => 'assign_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_otp_order', 'display_title' => 'assign_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_otp_order', 'display_title' => 'assign_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'send_rate_order', 'display_title' => 'assign_service_provider', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_address', 'display_title' => 'show_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_address', 'display_title' => 'add_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_address', 'display_title' => 'edit_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_address', 'display_title' => 'delete_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_client_packages', 'display_title' => 'show_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_client_packages', 'display_title' => 'add_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_client_packages', 'display_title' => 'edit_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_client_packages', 'display_title' => 'delete_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_Vehicle', 'display_title' => 'show_address', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_Vehicle', 'display_title' => 'add_Vehicle', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_Vehicle', 'display_title' => 'edit_Vehicle', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_Vehicle', 'display_title' => 'delete_Vehicle', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_balance_warehouse', 'display_title' => 'show_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balance_warehouse', 'display_title' => 'add_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balance_warehouse', 'display_title' => 'edit_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balance_warehouse', 'display_title' => 'delete_balance_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_balance_service_provider', 'display_title' => 'show_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balance_service_provider', 'display_title' => 'add_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balance_service_provider', 'display_title' => 'edit_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balance_service_provider', 'display_title' => 'delete_balance_delegate_res', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Qrcode_goods', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_Orders_rules', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_Orders_rules', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_Orders_rules', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_Orders_rules', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_CityZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_CityZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_CityZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_CityZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_RegionZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_RegionZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_RegionZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_RegionZone', 'display_title' => 'Qrcode_goods', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_order_warehouse', 'display_title' => 'show order warehouse', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_order_warehouse', 'display_title' => 'add order warehouse', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_order_warehouse', 'display_title' => 'edit order warehouse', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_order_warehouse', 'display_title' => 'delete order warehouse', 'created_at' => now(), 'updated_at' => now()],
            // show_api_fulfillment
            ['title' => 'show_api_fulfillment', 'display_title' => 'show api fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_api_fulfillment', 'display_title' => 'Add api fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_api_fulfillment', 'display_title' => 'Delete api fulfillment', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_order_fulfillment', 'display_title' => 'show order fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_order_fulfillment', 'display_title' => 'add order fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_order_fulfillment', 'display_title' => 'edit order fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_order_fulfillment', 'display_title' => 'delete order fulfillment', 'created_at' => now(), 'updated_at' => now()],

            //
            ['title' => 'show_client_fulfillment', 'display_title' => 'View  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_client_fulfillment', 'display_title' => 'Add  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_client_fulfillment', 'display_title' => 'Edit  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_client_fulfillment', 'display_title' => 'Delete  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'show_packaging_goods', 'display_title' => 'packaging_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_packaging_goods', 'display_title' => 'packaging_goods', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_packaging_goods', 'display_title' => 'packaging_goods', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_box', 'display_title' => 'View  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_box', 'display_title' => 'Add  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_box', 'display_title' => 'Edit  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_box', 'display_title' => 'Delete  fulfillment Client', 'created_at' => now(), 'updated_at' => now()],
            //
            ['title' => 'show_balance_fulfillment', 'display_title' => 'show_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_balance_fulfillment', 'display_title' => 'add_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_balance_fulfillment', 'display_title' => 'edit_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_balance_fulfillment', 'display_title' => 'delete_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],

            ['title' => 'show_orders_rules_service_provider', 'display_title' => 'show_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_orders_rules_service_provider', 'display_title' => 'add_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_orders_rules_service_provider', 'display_title' => 'edit_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_orders_rules_service_provider', 'display_title' => 'delete_balance_fulfillment', 'created_at' => now(), 'updated_at' => now()],

            //
            ['title' => 'show_pickup_order_warehouse', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_pickup_order_warehouse', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_pickup_order_warehouse', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_pickup_order_warehouse', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],

            ['title' => 'show_pickup_order_fulfillment', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_pickup_order_fulfillment', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_pickup_order_fulfillment', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_pickup_order_fulfillment', 'display_title' => 'View Order', 'created_at' => now(), 'updated_at' => now()],

            //
            ['title' => 'show_partners_statuses', 'display_title' => 'show_partners_statuses', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_partners_statuses', 'display_title' => 'add_partners_statuses', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_partners_statuses', 'display_title' => 'edit_partners_statuses', 'created_at' => now(), 'updated_at' => now()],
            // 
            ['title' => 'report_order_lastmile', 'display_title' => 'report_order_lastmile', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'report_order_resturant', 'display_title' => 'report_order_resturant', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'report_order_fulfillment', 'display_title' => 'report_order_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'report_accounting_lastmile', 'display_title' => 'report_accounting_lastmile', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'report_accounting_resturant', 'display_title' => 'report_accounting_resturant', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'report_accounting_fulfillment', 'display_title' => 'report_accounting_fulfillment', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'report_accounting_cod', 'display_title' => 'report_accounting_cod', 'created_at' => now(), 'updated_at' => now()],

            ['title' => 'scan_order_last_mile', 'display_title' => 'report_accounting_cod', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'scan_order_restaurant', 'display_title' => 'report_accounting_cod', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'scan_order_warehouse', 'display_title' => 'report_accounting_cod', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'scan_order_Fulfilmant', 'display_title' => 'report_accounting_cod', 'created_at' => now(), 'updated_at' => now()],

            ['title' => 'show_damagened_orders', 'display_title' => 'show_damaged_orders', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_damaged_orders', 'display_title' => 'add_damaged_orders', 'created_at' => now(), 'updated_at' => now()],
           
            ['title' => 'show_return_order_ful', 'display_title' => 'show_return_order_ful', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'add_return_order_ful', 'display_title' => 'add_return_order_ful', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'edit_return_order_ful', 'display_title' => 'edit_return_order_ful', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_return_order_ful', 'display_title' => 'delete_return_order_ful', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'delete_damaged_orders', 'display_title' => 'add_damaged_orders', 'created_at' => now(), 'updated_at' => now()],



           
        

        ];

        DB::table('permissions')->insert($permissions);
    }
}
